// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: bidirectionrpc/bidirectionrpc.proto

package bidirectionrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StreamingRequest) Reset() {
	*x = StreamingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidirectionrpc_bidirectionrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingRequest) ProtoMessage() {}

func (x *StreamingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bidirectionrpc_bidirectionrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingRequest.ProtoReflect.Descriptor instead.
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return file_bidirectionrpc_bidirectionrpc_proto_rawDescGZIP(), []int{0}
}

func (x *StreamingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StreamingResponse) Reset() {
	*x = StreamingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidirectionrpc_bidirectionrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingResponse) ProtoMessage() {}

func (x *StreamingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bidirectionrpc_bidirectionrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingResponse.ProtoReflect.Descriptor instead.
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return file_bidirectionrpc_bidirectionrpc_proto_rawDescGZIP(), []int{1}
}

func (x *StreamingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_bidirectionrpc_bidirectionrpc_proto protoreflect.FileDescriptor

var file_bidirectionrpc_bidirectionrpc_proto_rawDesc = []byte{
	0x0a, 0x23, 0x62, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x72, 0x70, 0x63,
	0x2f, 0x62, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x62, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x72, 0x70, 0x63, 0x22, 0x2c, 0x0a, 0x10, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x2d, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x7b, 0x0a, 0x12, 0x42, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x65, 0x0a, 0x18, 0x42, 0x69, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67,
	0x43, 0x61, 0x6c, 0x6c, 0x12, 0x20, 0x2e, 0x62, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x62, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x62, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bidirectionrpc_bidirectionrpc_proto_rawDescOnce sync.Once
	file_bidirectionrpc_bidirectionrpc_proto_rawDescData = file_bidirectionrpc_bidirectionrpc_proto_rawDesc
)

func file_bidirectionrpc_bidirectionrpc_proto_rawDescGZIP() []byte {
	file_bidirectionrpc_bidirectionrpc_proto_rawDescOnce.Do(func() {
		file_bidirectionrpc_bidirectionrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_bidirectionrpc_bidirectionrpc_proto_rawDescData)
	})
	return file_bidirectionrpc_bidirectionrpc_proto_rawDescData
}

var file_bidirectionrpc_bidirectionrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bidirectionrpc_bidirectionrpc_proto_goTypes = []any{
	(*StreamingRequest)(nil),  // 0: bidirectionrpc.StreamingRequest
	(*StreamingResponse)(nil), // 1: bidirectionrpc.StreamingResponse
}
var file_bidirectionrpc_bidirectionrpc_proto_depIdxs = []int32{
	0, // 0: bidirectionrpc.BidirectionService.BidirectionStreamingCall:input_type -> bidirectionrpc.StreamingRequest
	1, // 1: bidirectionrpc.BidirectionService.BidirectionStreamingCall:output_type -> bidirectionrpc.StreamingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bidirectionrpc_bidirectionrpc_proto_init() }
func file_bidirectionrpc_bidirectionrpc_proto_init() {
	if File_bidirectionrpc_bidirectionrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bidirectionrpc_bidirectionrpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StreamingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bidirectionrpc_bidirectionrpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*StreamingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bidirectionrpc_bidirectionrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bidirectionrpc_bidirectionrpc_proto_goTypes,
		DependencyIndexes: file_bidirectionrpc_bidirectionrpc_proto_depIdxs,
		MessageInfos:      file_bidirectionrpc_bidirectionrpc_proto_msgTypes,
	}.Build()
	File_bidirectionrpc_bidirectionrpc_proto = out.File
	file_bidirectionrpc_bidirectionrpc_proto_rawDesc = nil
	file_bidirectionrpc_bidirectionrpc_proto_goTypes = nil
	file_bidirectionrpc_bidirectionrpc_proto_depIdxs = nil
}
